# Image client: Client-Knoten (client1, attacker, ro-client1, ro-client2)
FROM alpine:3.20

RUN apk add --no-cache \
      iproute2 \
      curl \
      tcpdump \
      wireguard-tools

CMD ["sleep", "infinity"]
