# Image fw: Firewall-Knoten (fw-edge, fw-dmz, fw-backend)
FROM alpine:3.20

RUN apk add --no-cache \
      iproute2 \
      nftables \
      ulogd \
      tcpdump \
      wireguard-tools

CMD ["sleep", "infinity"]
